Repository openrazer/openrazer, pull requests merged in 2020-04, with the labels that each got.

#1067 Add support for Abyssus Elite (D.Va Edition)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerabyssuselitedvaedition.cfg
Labels: Device Support

#1068 Add support for Abyssus Essential
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerabyssusessential.cfg
Labels: Device Support

#1072 Custom matrix effect for orbweaver chroma keypad
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
Labels: enhancement

#1080 Add support for Razer DeathAdder Essential (White Edition)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerdeathadderessentialwhiteedition.cfg
Labels: Device Support

#1079 pylib: add some methods for battery
  pylib/openrazer/client/devices/mice.py
Labels: enhancement

#1087 pylib: add properties for keypad leds
  pylib/openrazer/client/devices/__init__.py
  pylib/openrazer/client/devices/keyboard.py
Labels: enhancement

#1094 Add support for Basilisk
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbasilisk.cfg
Labels: Device Support

#1105 Polling rate support for Abyssus 2014
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
Labels: Device Support, enhancement

#1103 Add support for Razer Viper
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerviper.cfg
Labels: Device Support
