Repository openrazer/openrazer, pull requests merged in 2020-01, with the labels that each got.

#939 Adding support for Razer DeathAdder 1800
  .gitignore
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#943 Add support for Razer Naga 2012
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#792 Add support for Razer Huntsman
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support, In Progress, awaiting response

#981 add support for Razer Firefly Hyperflux
  README.md
  daemon/openrazer_daemon/hardware/mouse_mat.py
  driver/razermousemat_driver.c
  driver/razermousemat_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  scripts/driver/firefly_hyperflux/test.py
Labels: Device Support

#950 Add Razer 15 mid 2019 base model.
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#962 Add support for Razer Blade Stealth Late 2019
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#985 Add support for Razer Blade 15 Studio Edition
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support, awaiting response
