Repository openrazer/openrazer, pull requests merged in 2020-03, with the labels that each got.

#976 Razer Tartarus v2 Lighting Support
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razertartarusv2.cfg
  pylib/openrazer/client/macro.py
Labels: Device Support

#1003 Add Razer Chroma HDK support to accessory driver
  README.md
  daemon/openrazer_daemon/dbus_services/dbus_methods/__init__.py
  daemon/openrazer_daemon/dbus_services/dbus_methods/accessory.py
  daemon/openrazer_daemon/dbus_services/dbus_methods/all.py
  daemon/openrazer_daemon/hardware/accessory.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/udev/99-razer.rules
Labels: Device Support

#1043 Add support for Razer Base Station Chroma
  README.md
  daemon/openrazer_daemon/hardware/accessory.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#1036 Add support for Razer Mamba Wireless
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razermambawirelessreceiver.cfg
  pylib/openrazer/_fake_driver/razermambawirelesswired.cfg
Labels: Device Support

#1044 Add support for Razer Blade Pro (Late 2019) 1532:024C
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#1049 razerkbd: fix fn key on some devices
  driver/razerkbd_driver.c
Labels: bug, need testing

#1010 Add support for Huntsman Tournament Edition
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#978 Add support rbg starlight for blade kbd and others
  driver/razerkbd_driver.c
Labels: enhancement
