Repository openrazer/openrazer, pull requests merged in 2020-05, with the labels that each got.

#1061 Razer Nommo Pro and Razer Nommo Chroma support
  README.md
  daemon/openrazer_daemon/hardware/accessory.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/udev/99-razer.rules
Labels: Device Support

#887 Add support for Razer Lancehead
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerlancehead.cfg
  pylib/openrazer/_fake_driver/razerlanceheadwired.cfg
Labels: Device Support, need testing

#1128 Fix razer_chroma_misc_get_dpi_xy
  driver/razerchromacommon.c
Labels: bug

#1055 Add support for Razer Lancehead Wireless (2019)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerlanceheadwirelessreceiver.cfg
  pylib/openrazer/_fake_driver/razerlanceheadwirelesswired.cfg
Labels: Device Support

#1093 Initial support for Razer DeathAdder V2
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
Labels: Device Support

#1075 Fix for Razer Mamba Wireless
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  pylib/openrazer/_fake_driver/razermambawirelessreceiver.cfg
  pylib/openrazer/_fake_driver/razermambawirelesswired.cfg
Labels: enhancement

#1131 Add support for Kraken Ultimate [headset]
  README.md
  daemon/openrazer_daemon/hardware/headsets.py
  driver/razerkraken_driver.c
  driver/razerkraken_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerkrakenultimate.cfg
Labels: Device Support
