Repository openrazer/openrazer, pull requests merged in 2021-01, with the labels that each got.

#1372 Add support for the Ornata Chroma V2
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerornatachromav2.cfg
Labels: Device Support

#1399 Check for double interface in razeraccessory driver
  driver/razeraccessory_driver.c
Labels: bug

#1368 Support DeathAdder V2 Mini
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerdeathadderv2mini.cfg
Labels: Device Support

#1403 Adds Base Station V2 Chroma Support
  README.md
  daemon/openrazer_daemon/hardware/accessory.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbasestationv2chroma.cfg
Labels: Device Support

#1123 Add support for Razer Firefly V2
  README.md
  daemon/openrazer_daemon/hardware/mouse_mat.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerfireflyv2.cfg
  scripts/driver/firefly_v2/test.py
Labels: Device Support, In Progress, need testing

#1363 driver: razerkbd: fix fn processing in raw_event for newer devices
  driver/razerkbd_driver.c
Labels: help wanted, need testing
