Repository openrazer/openrazer, pull requests merged in 2021-10, with the labels that each got.

#1580 Proposal: don't use varstore for custom frames
  driver/razerkbd_driver.c
Labels: enhancement

#1602 DRAFT: Changed dbus-user-session dependency to dbus-session-bus
  debian/control
Labels: enhancement

#1597 Razer Naga 2014 REL_HWHEEL event support
  driver/razermouse_driver.c
  pylib/openrazer/_fake_driver/razernaga2014.cfg
Labels: enhancement

#1586 Add support for Razer Blade 14 (2021)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade142021.cfg
Labels: Device Support

#1604 daemon: Add missing brightness controls for Razer Naga Chroma
  daemon/openrazer_daemon/hardware/mouse.py
Labels: bug

#1376 Keyboard Support of the Razer Blade Pro Early 2020
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbladeproearly2020.cfg
Labels: Device Support

#1651 Add support for blade 17 pro mid 2021 keyboard lighting
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade17promid2021.cfg
Labels: Device Support

#1572 Add support for BlackWidow V3 (Full Size)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  driver/usb_hid_keys.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblackwidowv3.cfg
Labels: Device Support

#1635 Add Razer Thunderbolt 4 Dock Chroma Support
  README.md
  daemon/openrazer_daemon/hardware/accessory.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerthunderbolt4dockchroma.cfg
Labels: Device Support

#1633 Add support for Razer Viper 8KHz
  README.md
  daemon/openrazer_daemon/dbus_services/dbus_methods/mamba.py
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razerchromacommon.c
  driver/razerchromacommon.h
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerviper8khz.cfg
  pylib/openrazer/client/constants.py
  pylib/openrazer/client/devices/__init__.py
  pylib/openrazer/client/devices/mice.py
Labels: Device Support
