Repository openrazer/openrazer, pull requests merged in 2021-03, with the labels that each got.

#1321 Add Basilisk Ultimate and Mouse Dock support
  README.md
  daemon/openrazer_daemon/hardware/accessory.py
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbasiliskultimatereceiver.cfg
  pylib/openrazer/_fake_driver/razerbasiliskultimatewired.cfg
  pylib/openrazer/_fake_driver/razermousedock.cfg
Labels: Device Support, need testing

#1407 Adds Razer Charging Pad Chroma Support
  README.md
  daemon/openrazer_daemon/dbus_services/dbus_methods/__init__.py
  daemon/openrazer_daemon/dbus_services/dbus_methods/charging_pad_chroma.py
  daemon/openrazer_daemon/hardware/accessory.py
  daemon/openrazer_daemon/hardware/device_base.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  driver/razerchromacommon.c
  driver/razercommon.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerchargingpadchroma.cfg
  pylib/openrazer/client/devices/__init__.py
  pylib/openrazer/client/fx.py
  scripts/generate_fake_driver.sh
Labels: Device Support

#1431 Add support for keyboard: Huntsman Mini
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerhuntsmanmini.cfg
Labels: Device Support

#1468 Add fn translate keys for huntsman mini keyboard
  driver/razerkbd_driver.c
Labels: bug

#1475 Remove Gdk dependency
  daemon/openrazer_daemon/daemon.py
  daemon/openrazer_daemon/keyboard.py
Labels: bug
