Repository openrazer/openrazer, pull requests merged in 2022-07, with the labels that each got.

#1849 driver: add support for Razer Viper V2 Pro
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerviperv2prowired.cfg
  pylib/openrazer/_fake_driver/razerviperv2prowireless.cfg
Labels: Device Support

#1848 daemon: Write persistence when Y=0 for DPI X only devices
  daemon/openrazer_daemon/daemon.py
Labels: bug

#1861 udev: Check binding for 'razer' driver in addition to 'hid-generic'
  install_files/udev/razer_mount
Labels: bug

#1863 daemon: Initialize Y=0 for DPI X only devices
  daemon/openrazer_daemon/hardware/device_base.py
Labels: bug

#1857 (mostly) copy from huntsman v2 analog for huntsman mini analog
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerhuntsmanminianalog.cfg
Labels: Device Support

#1859 Add support for the DeathAdder 3.5G Black
  README.md
  daemon/openrazer_daemon/hardware/device_base.py
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerdeathadder3.5gblack.cfg
Labels: Device Support

#1759 Adds Additional Support for the Razer Huntsman V2
  daemon/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerchromacommon.c
  driver/razerchromacommon.h
  driver/razerkbd_driver.c
  pylib/openrazer/_fake_driver/razerhuntsmanv2.cfg
  pylib/openrazer/client/constants.py
  pylib/openrazer/client/devices/__init__.py
  pylib/openrazer/client/devices/keyboard.py
  scripts/generate_fake_driver.sh
Labels: enhancement, Device Support
