Repository openrazer/openrazer, pull requests merged in 2022-04, with the labels that each got.

#1674 Adds Razer Huntsman V2 Support
  README.md
  daemon/openrazer_daemon/dbus_services/dbus_methods/mamba.py
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerhuntsmanv2.cfg
Labels: Device Support

#1692 Add Razer Naga Pro Wired/Wireless Support
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razernagaprowired.cfg
  pylib/openrazer/_fake_driver/razernagaprowireless.cfg
Labels: Device Support

#1764 Raptor 27 Support
  README.md
  daemon/openrazer_daemon/hardware/monitor.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerraptor27.cfg
Labels: Device Support

#1695 Add support for Razer Naga Epic Chroma
  README.md
  daemon/openrazer_daemon/dbus_services/dbus_methods/deathadder_chroma.py
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razernagaepicchroma.cfg
  pylib/openrazer/_fake_driver/razernagaepicchromadock.cfg
  scripts/generate_fake_driver.sh
Labels: Device Support

#1734 Add support for Razer Basilisk V3 scroll wheel settings
  daemon/openrazer_daemon/dbus_services/dbus_methods/__init__.py
  daemon/openrazer_daemon/dbus_services/dbus_methods/mouse_scroll_wheel.py
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razerchromacommon.c
  driver/razerchromacommon.h
  driver/razermouse_driver.c
  pylib/openrazer/_fake_driver/razerbasiliskv3.cfg
  pylib/openrazer/client/devices/__init__.py
  pylib/openrazer/client/devices/mice.py
  scripts/generate_fake_driver.sh
Labels: enhancement

#1779 Added support for Razer Blade 17 (2022)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade172022.cfg
Labels: Device Support

#1769 DeathAdder 2000 image loads through https
  daemon/openrazer_daemon/hardware/mouse.py
Labels: enhancement

#1766 Add 2022 blade 15 support
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade15advancedearly2022.cfg
Labels: Device Support

#1788 feature: implement razer pro click support
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerproclickreceiver.cfg
  pylib/openrazer/_fake_driver/razerproclickwired.cfg
Labels: Device Support

#1790 Fix oob memcpy matrix custom frame
  driver/razerchromacommon.c
Labels: bug
