Repository openrazer/openrazer, pull requests merged in 2022-01, with the labels that each got.

#1555 Add support for Razer Orochi V2
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerorochiv2bluetooth.cfg
  pylib/openrazer/_fake_driver/razerorochiv2receiver.cfg
Labels: Device Support

#1710 daemon: Fix missing battery notifications for some devices
  daemon/openrazer_daemon/hardware/mouse.py
Labels: bug

#1666 Improve battery notification presentation & add option to configure % threshold
  daemon/openrazer_daemon/hardware/keyboards.py
  daemon/openrazer_daemon/hardware/mouse.py
  daemon/openrazer_daemon/misc/battery_notifier.py
  daemon/resources/man/razer.conf.5
  daemon/resources/man/razer.conf.5.scd
  daemon/resources/razer.conf
Labels: enhancement

#1655 Make ORNATA V2 keyboard to use the bitfield raw_event
  driver/razerkbd_driver.c
Labels: enhancement

#1703 Add basic support for Razer Basilisk V3
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razerchromacommon.c
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbasiliskv3.cfg
  scripts/razer_mouse/driver/set_mouse_dpi.py
Labels: Device Support

#1687 Add support for Huntsman Mini JP
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerhuntsmanminijp.cfg
Labels: Device Support
