Repository openrazer/openrazer, pull requests merged in 2023-08, with the labels that each got.

#2095 Add get_idle_time and get_low_battery_threshold methods to Viper Ult
  daemon/openrazer_daemon/hardware/mouse.py
Labels: enhancement

#2057 Add support for Razer DeathAdder V3
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerdeathadderv3.cfg
Labels: Device Support, help wanted

#2097 Add USB_DEVICE_ID_RAZER_NAGA_CHROMA to list of devices supporting horizontal scrolling
  driver/razermouse_driver.c
  pylib/openrazer/_fake_driver/razernagachroma.cfg
Labels: bug

#2072 Fixed self-assignment code
  driver/razerchromacommon.c
Labels: enhancement

#2020 daemon: restore keyboard driver mode on resume
  daemon/openrazer_daemon/hardware/keyboards.py
Labels: enhancement

#1881 add install_requires to setup.py
  daemon/setup.py
  pylib/setup.py
Labels: packaging

#2037 Add support for 2023 16/18 Blade models.
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade162023.cfg
  pylib/openrazer/_fake_driver/razerblade182023.cfg
Labels: Device Support

#2075 Add effect example based on CPU temperature
  examples/cpu_temperature.py
Labels: enhancement

#2117 daemon: notify for new effect when calling setCustom/setKeyRow
  daemon/openrazer_daemon/dbus_services/dbus_methods/chroma_keyboard.py
  daemon/openrazer_daemon/hardware/device_base.py
  daemon/openrazer_daemon/misc/ripple_effect.py
Labels: bug, need testing
