Repository openrazer/openrazer, pull requests merged in 2024-07, with the labels that each got.

#2239 Add support for DeathAdder V3 Pro (00c2/00c3)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerdeathadderv3prowired_2.cfg
  pylib/openrazer/_fake_driver/razerdeathadderv3prowireless_2.cfg
  scripts/generate_fake_driver.sh
Labels: Device Support

#2262 Add `persistence_dual_boot_quirk` to razer.conf
  daemon/openrazer_daemon/daemon.py
  daemon/openrazer_daemon/hardware/device_base.py
  daemon/resources/man/razer.conf.5
  daemon/resources/man/razer.conf.5.scd
  daemon/resources/razer.conf
Labels: enhancement

#2248 Ignore battery level zero when notifying
  daemon/openrazer_daemon/misc/battery_notifier.py
Labels: bug, enhancement

#2260 Add support for Ornata V3 TKL
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerornatav3tenkeyless.cfg
Labels: Device Support

#2266 Add support for Razer Viper V3 Pro (Wired and Wireless)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razerchromacommon.c
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerviperv3prowired.cfg
  pylib/openrazer/_fake_driver/razerviperv3prowireless.cfg
Labels: Device Support

#2269 Support for Blackwidow V4 X
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblackwidowv4x.cfg
Labels: Device Support

#1289 Add support for Razer Naga Epic
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razernagaepic.cfg
Labels: Device Support

#2241 Add support for Razer Blade 14 (2024)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade142024.cfg
Labels: Device Support
