Repository openrazer/openrazer, pull requests merged in 2024-09, with the labels that each got.

#2296 Replace notify2 dependency used in battery notifier
  DEVELOPMENT.md
  daemon/openrazer_daemon/misc/battery_notifier.py
  debian/control
Labels: bug

#2281 Add support for Razer Goliathus Chroma 3XL
  README.md
  daemon/openrazer_daemon/hardware/mouse_mat.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razergoliathuschroma3xl.cfg
Labels: Device Support

#2287 Support for BlackWidow V4 75%
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblackwidowv475pct.cfg
  scripts/generate_fake_driver.sh
Labels: Device Support

#2300 Fix Razer BlackWidow V4 75% Fn+KEY combinations not working
  driver/razerkbd_driver.c
Labels: enhancement

#2233 Add support for Razer Ornata V3 [028F]
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerornatav3_2.cfg
  scripts/generate_fake_driver.sh
Labels: Device Support
