Repository openrazer/openrazer, pull requests merged in 2024-04, with the labels that each got.

#2190 Add support for Razer Cobra Pro (Wired)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razercobraprowired.cfg
  pylib/openrazer/_fake_driver/razercobraprowireless.cfg
Labels: Device Support

#2225 driver: Add low threshold support for DeathAdder V3 Pro
  driver/razermouse_driver.c
Labels: bug

#1737 Add support for Razer Blade 15 Advanced (Late 2019)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbladeadvancedlate2019.cfg
Labels: need testing, Device Support

#2211 Add support for Razer BlackWidow V4
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  daemon/openrazer_daemon/keyboard.py
  daemon/openrazer_daemon/misc/key_event_management.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblackwidowv4.cfg
Labels: Device Support

#2189 Add 8k option for hyperpolling dongle
  daemon/openrazer_daemon/hardware/mouse.py
Labels: enhancement

#2182 Add Support for Razer Ornata V3 (02A1)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerornatav3.cfg
Labels: Device Support

#2237 Add support for Razer Blade 14 (2023)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade142023.cfg
Labels: Device Support
