Repository openrazer/openrazer, pull requests merged in 2025-05, with the labels that each got.

#2452 driver: Update set_bit code to use DECLARE_BITMAP
  driver/razerkbd_driver.c
Labels: bug, need testing

#2459 added BW Ultimate 2012 to chroma_keys_2 in razer_event()
  driver/razerkbd_driver.c
Labels: bug

#2447 razerkbd: Add support for 48 byte long raw events
  driver/razerkbd_driver.c
Labels: enhancement
