Repository openrazer/openrazer, pull requests merged in 2025-02, with the labels that each got.

#2220 Fix persistence for devices with UNKWN00000000xxxx serial number
  daemon/openrazer_daemon/daemon.py
  daemon/openrazer_daemon/hardware/device_base.py
Labels: enhancement

#2355 daemon: Fix keyboard layout lookup for Turkish, Japanese and Swiss
  daemon/openrazer_daemon/dbus_services/dbus_methods/all.py
Labels: bug

#2363 Feature: Add support for Razer Basilisk V3 35K (non-Pro version)
  README.md
  daemon/openrazer_daemon/hardware/mouse.py
  driver/razermouse_driver.c
  driver/razermouse_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerbasiliskv335k.cfg
Labels: Device Support

#2375 Add support for Razer Blade 18 2024 (1532:02B8)
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade182024.cfg
Labels: Device Support

#2365 Add support for Razer Huntsman V3 Pro
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerhuntsmanv3pro.cfg
Labels: Device Support

#2400 Added Razer Blade 15 Late 2020 Support
  README.md
  daemon/openrazer_daemon/hardware/keyboards.py
  driver/razerkbd_driver.c
  driver/razerkbd_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerblade15baselate2020.cfg
Labels: Device Support
