Repository openrazer/openrazer, pull requests merged in 2025-07, with the labels that each got.

#2470 razerkbd: Add correct key translation for Ornata V3 Tenkeyless
  driver/razerkbd_driver.c
Labels: need testing

#2416 daemon: Add DRIVER_MODE variable
  daemon/openrazer_daemon/hardware/device_base.py
  daemon/openrazer_daemon/hardware/keyboards.py
Labels: bug

#2480 Add support for Razer Firefly V2 Pro
  README.md
  daemon/openrazer_daemon/hardware/mouse_mat.py
  driver/razeraccessory_driver.c
  driver/razeraccessory_driver.h
  install_files/appstream/io.github.openrazer.openrazer.metainfo.xml
  install_files/udev/99-razer.rules
  pylib/openrazer/_fake_driver/razerfireflyv2pro.cfg
Labels: Device Support

#2456 Apply driver mode to fix scroll click for Basilisk V3 X HyperSpeed
  daemon/openrazer_daemon/hardware/mouse.py
Labels: Device Quirk
